fix build

diff --git a/packages/ai/sami/Dockerfile b/packages/ai/sami/Dockerfile
--- a/packages/ai/sami/Dockerfile
+++ b/packages/ai/sami/Dockerfile
@@ -22,7 +22,9 @@ COPY tsconfig.json ./
 # Copy the rest of the application code
 COPY ./src ./src
 COPY ./characters ./characters
-COPY ./.env ./
+
+# Copia el .env solo si existe
+RUN test -f .env && cp .env /app/.env || echo ".env not found, skipping."
 
 # Install dependencies and build the project
 RUN pnpm i
@@ -44,10 +46,12 @@ COPY --from=builder /app/package.json /app/
 COPY --from=builder /app/node_modules /app/node_modules
 COPY --from=builder /app/src /app/src
 COPY --from=builder /app/characters /app/characters
-COPY --from=builder /app/.env /app/
 COPY --from=builder /app/dist /app/dist
 COPY --from=builder /app/tsconfig.json /app/
 COPY --from=builder /app/pnpm-lock.yaml /app/
+
+# Copia el .env solo si existe
+RUN test -f .env && cp .env /app/.env || echo ".env not found, skipping."
 
 EXPOSE 3000
 # Set the command to run the application
